# Generated by Django 5.0.2 on 2024-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicles',
            field=models.ManyToManyField(related_name='owners', to='REST.vehicle'),
        ),
    ]
