# Generated by Django 5.0.2 on 2024-02-08 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0003_user_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('smoke', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receivers', models.ManyToManyField(related_name='alerts_received', to='REST.vehicle')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='REST.vehicle')),
            ],
        ),
    ]
