# Generated by Django 5.0.2 on 2024-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0004_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='recent',
            field=models.BooleanField(default=0),
        ),
    ]
