# Generated by Django 5.0.2 on 2024-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0005_alert_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='receivers',
            field=models.ManyToManyField(default=None, related_name='alerts_received', to='REST.vehicle'),
        ),
    ]
