# Generated by Django 5.0.2 on 2024-02-12 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0011_remove_user_cover_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2024, 2, 12, 13, 7, 8, 223657, tzinfo=datetime.timezone.utc)),
        ),
    ]
