# Generated by Django 5.0.2 on 2024-02-12 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0012_vehicle_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_update',
            field=models.TimeField(default=datetime.datetime(2024, 2, 12, 21, 29, 30, 88806, tzinfo=datetime.timezone.utc)),
        ),
    ]
