# Generated by Django 5.0.2 on 2024-02-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0014_alter_vehicle_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='s',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='t',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='u',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='umidity',
            field=models.FloatField(default=0),
        ),
    ]
