# Generated by Django 5.0.2 on 2024-02-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0015_alert_humidity_alert_s_alert_t_alert_u_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='humidity',
            new_name='umidity',
        ),
    ]
