# Generated by Django 5.0.2 on 2024-02-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0016_rename_humidity_alert_umidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='t',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='u',
            field=models.IntegerField(default=0),
        ),
    ]
